{% set name = "kartograf" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kartograf-{{ version }}.tar.gz
  sha256: 7fae33b54cb533d7ec81b0a8b61c4ebd87697d2105e4ff9e5ad086bfcdfe0b28

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools >=61.0
    - versioningit
  run:
    - numpy
    - python >=3.9
    - rdkit
    - scipy
    - gufe

test:
  imports:
    - kartograf
  requires:
    - pip
    - pytest
    - py3Dmol
  commands:
    - pytest --pyargs kartograf

about:
  home: https://github.com/OpenFreeEnergy/kartograf
  summary: Kartograf is a package for mapping geometrically atoms of two molecules. (like you need it with hybrid topology)
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dwhswenson
    - ialibay
    - mikemhenry
    - richardjgowers
    - riesben
