{% set name = "kartograf" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kartograf-{{ version }}.tar.gz
  sha256: 9ba7f108e116c1c37721c385cc1caeb176d4c54076b07df8d29660699a5f6ee2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools >=61.0
    - versioningit
  run:
    - dill
    - gufe >=0.10
    - numpy
    - py3Dmol
    - python >=3.9
    - rdkit
    - scipy

test:
  imports:
    - kartograf
  requires:
    - pip
    - pytest
  commands:
    - pytest --pyargs kartograf

about:
  home: https://github.com/OpenFreeEnergy/kartograf
  summary: Kartograf is a package for mapping geometrically atoms of two molecules. (like you need it with hybrid topology)
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jthorton
    - dwhswenson
    - ialibay
    - mikemhenry
    - richardjgowers
    - riesben
